"""empty message

Revision ID: 4f611d011648
Revises: 4d16c0eeba29
Create Date: 2020-12-29 15:06:43.734466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f611d011648'
down_revision = '4d16c0eeba29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('hbu_saudi')
    # op.drop_table('zero_price_level')
    # with op.batch_alter_table('init_data', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('base_value_sales', sa.Float(), nullable=True))
    #     batch_op.add_column(sa.Column('base_value_share', sa.Float(), nullable=True))
    #     batch_op.add_column(sa.Column('diff_value_sales', sa.Float(), nullable=True))
    #     batch_op.add_column(sa.Column('index_volume_share', sa.Float(), nullable=True))
    #     batch_op.add_column(sa.Column('new_value_sales', sa.Float(), nullable=True))
    #     batch_op.add_column(sa.Column('new_value_share', sa.Float(), nullable=True))
    #     batch_op.drop_column('revenue')
    #     batch_op.drop_column('old_wd')
    #     batch_op.drop_column('old_size')
    #     batch_op.drop_column('value_share')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('msu', sa.Float()))
        batch_op.add_column(sa.Column('vsu', sa.Float()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('vsu')
        batch_op.drop_column('msu')

    with op.batch_alter_table('init_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value_share', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('old_size', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('old_wd', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('revenue', sa.FLOAT(), nullable=True))
        batch_op.drop_column('new_value_share')
        batch_op.drop_column('new_value_sales')
        batch_op.drop_column('index_volume_share')
        batch_op.drop_column('diff_value_sales')
        batch_op.drop_column('base_value_share')
        batch_op.drop_column('base_value_sales')

    op.create_table('zero_price_level',
    sa.Column('sku_name', sa.TEXT(), nullable=True),
    sa.Column('zero_percent', sa.FLOAT(), nullable=True),
    sa.Column('project_id', sa.BIGINT(), nullable=True)
    )
    op.create_table('hbu_saudi',
    sa.Column('RespondentID', sa.BIGINT(), nullable=True),
    sa.Column('RespondentWeight', sa.BIGINT(), nullable=True),
    sa.Column('ALMARAI  TR.P  480GR', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI  TR.P  120GR', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI  TR.P  240GR', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI  TR.P  360GR', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI SQ 108GX3 (2+1 FR)', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI  SQ.P 432GR', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI SQ 216GX3 (SP.PR)', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAISQ 108G BOX', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI  SQ.P  216GR', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI BLU 500GX2 GLASS L/C(SP', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI BLU 900GX2 GLASS(SP.PR)', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI GOLD 500GX2 GLASS (SP.PR)', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI GOLD 900GX2 GLASS (SP.PR)', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI GLASS BLU  500GR', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI GLASS BLU  900GR', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI GLASS GOLD  500GR', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI SQ 432G (SP.PRICE)', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI SQ 432GX2 (SP.PRICE)', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI TR 120GX5 (1 Fr', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI TR 480GX2 (SP)', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI BLU 500GX2 GLASS(SP.PR)', sa.FLOAT(), nullable=True),
    sa.Column('LVQR  TR.P 120GR', sa.FLOAT(), nullable=True),
    sa.Column('LVQR  TR.P 480GR', sa.FLOAT(), nullable=True),
    sa.Column('LVQR  TR.P 360GR', sa.FLOAT(), nullable=True),
    sa.Column('LVQR  TR.P 240GR', sa.FLOAT(), nullable=True),
    sa.Column('LVQR TR 120GX5 (4+1 FR)', sa.FLOAT(), nullable=True),
    sa.Column('LVQR TR 480GX2(SP.PRICE)', sa.FLOAT(), nullable=True),
    sa.Column('LVQR  TUB 200GR', sa.FLOAT(), nullable=True),
    sa.Column('LVQR  TUB 500GR', sa.FLOAT(), nullable=True),
    sa.Column('JAW  TUB480GR', sa.FLOAT(), nullable=True),
    sa.Column('JAW  TR.P 480GR', sa.FLOAT(), nullable=True),
    sa.Column('JAW  TR.P 120GR', sa.FLOAT(), nullable=True),
    sa.Column('JAW  TR.P 240GR', sa.FLOAT(), nullable=True),
    sa.Column('JAW TR 120GX4 (S.P)', sa.FLOAT(), nullable=True),
    sa.Column('JAW TR 120GX5 (8PO)(SP)', sa.FLOAT(), nullable=True),
    sa.Column('PUCK  SQ.P 108GR', sa.FLOAT(), nullable=True),
    sa.Column('PUCK  SQ.P 216GR', sa.FLOAT(), nullable=True),
    sa.Column('PUCK  SQ.P 432GR', sa.FLOAT(), nullable=True),
    sa.Column('PUCK 500GX2 GLASS BLUE(SP.PRICE)', sa.FLOAT(), nullable=True),
    sa.Column('PUCK 910GX2 JAR BLUE (SP.PRICE)', sa.FLOAT(), nullable=True),
    sa.Column('PUCK GLASS BLU  240GR', sa.FLOAT(), nullable=True),
    sa.Column('PUCK GLASS BLU  500GR', sa.FLOAT(), nullable=True),
    sa.Column('PUCK GLASS BLU  910GR', sa.FLOAT(), nullable=True),
    sa.Column('PUCK GLASS BLU  1100GR', sa.FLOAT(), nullable=True),
    sa.Column('PUCK TR 120GX5 (4+1 FREE)', sa.FLOAT(), nullable=True),
    sa.Column('PUCK 650GR JAR(30% EXTR A) (BLUE)', sa.FLOAT(), nullable=True),
    sa.Column('SALIM  TR.P 120GR', sa.FLOAT(), nullable=True),
    sa.Column('PRESIDENT TR 120GX5 (4+1FR)', sa.FLOAT(), nullable=True),
    sa.Column('NADEC  TR.P 120GR', sa.FLOAT(), nullable=True),
    sa.Column('NADEC 500GX2 GLASS BLUE (SP.PRICE)', sa.FLOAT(), nullable=True),
    sa.Column('NADEC 500GX2 GLASS GOLD (SP PRICE)', sa.FLOAT(), nullable=True),
    sa.Column('NADEC GLASS BLU  500GR', sa.FLOAT(), nullable=True),
    sa.Column('NADEC TR 120GX5 (4+1 FREE)', sa.FLOAT(), nullable=True),
    sa.Column('KIRI SQ 216GX3 (SP. PRICE)', sa.FLOAT(), nullable=True),
    sa.Column('KIRI SQ 432GX2 (SP.P)', sa.FLOAT(), nullable=True),
    sa.Column('KIRI SQ 108GX5 (SP.P)', sa.FLOAT(), nullable=True),
    sa.Column('KIRI  SQ.P 324GR', sa.FLOAT(), nullable=True),
    sa.Column('KIRI  SQ.P 432GR', sa.FLOAT(), nullable=True),
    sa.Column('KIRI  SQ.P 108GR', sa.FLOAT(), nullable=True),
    sa.Column('KIRI  SQ.P 216GR', sa.FLOAT(), nullable=True),
    sa.Column('KIRI  TUB 350GR', sa.FLOAT(), nullable=True),
    sa.Column('KIRI  TUB 500GR', sa.FLOAT(), nullable=True),
    sa.Column('KIRI SQ 108GX5 (1 FREE)', sa.FLOAT(), nullable=True),
    sa.Column('KIRI SQ 432GX3(24P)(SP.P)', sa.FLOAT(), nullable=True),
    sa.Column('KRAFT GLASS480GX2 GOLD JAR(SP)', sa.FLOAT(), nullable=True),
    sa.Column('KRAFT 870GX2GOLD JAR(SP)', sa.FLOAT(), nullable=True),
    sa.Column('PHILADELPHIA  TUB 200GR', sa.FLOAT(), nullable=True),
    sa.Column('PHILADELPHIA  TUB 300GR', sa.FLOAT(), nullable=True),
    sa.Column('PHILADELPHIA  TUB  300GR', sa.FLOAT(), nullable=True),
    sa.Column('PHILADELPHIA  TUB 500GR', sa.FLOAT(), nullable=True),
    sa.Column('PHILADELPHIA  TUB 1650GR', sa.FLOAT(), nullable=True),
    sa.Column('PHILADELPHIA  TUB  200GR', sa.FLOAT(), nullable=True),
    sa.Column('JAW 8 PIECES 120 GR', sa.FLOAT(), nullable=True),
    sa.Column('JAW 480X2 32X2', sa.FLOAT(), nullable=True),
    sa.Column('KIRI SP Greek Style 6p', sa.FLOAT(), nullable=True),
    sa.Column('KIRI SP Greek style 24p', sa.FLOAT(), nullable=True),
    sa.Column('KIRI Jars 240g', sa.FLOAT(), nullable=True),
    sa.Column('KIRI Jars 440g', sa.FLOAT(), nullable=True),
    sa.Column('KIRI Jars 600g', sa.FLOAT(), nullable=True),
    sa.Column('KIRI Tubs Greek style 200g', sa.FLOAT(), nullable=True),
    sa.Column('KIRI Tubs Greek style 500g', sa.FLOAT(), nullable=True),
    sa.Column('JAW Jar 240g', sa.FLOAT(), nullable=True),
    sa.Column('JAW Jar 500g', sa.FLOAT(), nullable=True),
    sa.Column('JAW Jar 900g', sa.FLOAT(), nullable=True),
    sa.Column('LVQR TR.P Organic 8p', sa.FLOAT(), nullable=True),
    sa.Column('-0.4', sa.FLOAT(), nullable=True),
    sa.Column('-0.35', sa.FLOAT(), nullable=True),
    sa.Column('-0.3', sa.FLOAT(), nullable=True),
    sa.Column('-0.25', sa.FLOAT(), nullable=True),
    sa.Column('-0.2', sa.FLOAT(), nullable=True),
    sa.Column('-0.15', sa.FLOAT(), nullable=True),
    sa.Column('-0.1', sa.FLOAT(), nullable=True),
    sa.Column('-0.05', sa.FLOAT(), nullable=True),
    sa.Column('0', sa.FLOAT(), nullable=True),
    sa.Column('0.05', sa.FLOAT(), nullable=True),
    sa.Column('0.1', sa.FLOAT(), nullable=True),
    sa.Column('0.15', sa.FLOAT(), nullable=True),
    sa.Column('0.2', sa.FLOAT(), nullable=True),
    sa.Column('0.25', sa.FLOAT(), nullable=True),
    sa.Column('0.3', sa.FLOAT(), nullable=True),
    sa.Column('0.35', sa.FLOAT(), nullable=True),
    sa.Column('0.4', sa.FLOAT(), nullable=True)
    )
    # ### end Alembic commands ###
