"""empty message

Revision ID: a0324f1b870d
Revises: 
Create Date: 2020-12-10 19:48:52.291560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0324f1b870d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('init_data', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_init_data_sku_name'), ['sku_name'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_product_sku_name'), ['sku_name'])

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('hbu_filename',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('start_price',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_project_hbu_filename'), ['hbu_filename'])
        batch_op.create_unique_constraint(batch_op.f('uq_project_title'), ['title'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_project_title'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_project_hbu_filename'), type_='unique')
        batch_op.alter_column('start_price',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('hbu_filename',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_product_sku_name'), type_='unique')

    with op.batch_alter_table('init_data', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_init_data_sku_name'), type_='unique')

    # ### end Alembic commands ###
