"""empty message

Revision ID: c1d5793d2e49
Revises: f79334ee6bc0
Create Date: 2020-12-13 18:31:26.476592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d5793d2e49'
down_revision = 'f79334ee6bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hbu_saudi')
    op.drop_table('product')
    with op.batch_alter_table('init_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_size', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('old_sop', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('old_volume_share', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('old_wd', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('init_data', schema=None) as batch_op:
        batch_op.drop_column('old_wd')
        batch_op.drop_column('old_volume_share')
        batch_op.drop_column('old_sop')
        batch_op.drop_column('old_size')

    op.create_table('product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sku_name', sa.TEXT(), nullable=False),
    sa.Column('company', sa.INTEGER(), nullable=True),
    sa.Column('group_brand', sa.TEXT(), nullable=False),
    sa.Column('group_size', sa.INTEGER(), nullable=True),
    sa.Column('group_segments', sa.TEXT(), nullable=False),
    sa.Column('group_manufacturer', sa.TEXT(), nullable=False),
    sa.Column('market_share', sa.FLOAT(), nullable=True),
    sa.Column('wd', sa.FLOAT(), nullable=True),
    sa.Column('sales', sa.FLOAT(), nullable=True),
    sa.Column('base_price', sa.TEXT(), nullable=False),
    sa.Column('base_size', sa.FLOAT(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_name', name='uq_product_sku_name')
    )
    op.create_table('hbu_saudi',
    sa.Column('RespondentID', sa.BIGINT(), nullable=True),
    sa.Column('RespondentWeight', sa.BIGINT(), nullable=True),
    sa.Column('ALMARAI  TR.P  480GR', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI  TR.P  120GR', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI  TR.P  240GR', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI  TR.P  360GR', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI SQ 108GX3 (2+1 FR)', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI  SQ.P 432GR', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI SQ 216GX3 (SP.PR)', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAISQ 108G BOX', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI  SQ.P  216GR', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI BLU 500GX2 GLASS L/C(SP', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI BLU 900GX2 GLASS(SP.PR)', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI GOLD 500GX2 GLASS (SP.PR)', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI GOLD 900GX2 GLASS (SP.PR)', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI GLASS BLU  500GR', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI GLASS BLU  900GR', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI GLASS GOLD  500GR', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI SQ 432G (SP.PRICE)', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI SQ 432GX2 (SP.PRICE)', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI TR 120GX5 (1 Fr', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI TR 480GX2 (SP)', sa.FLOAT(), nullable=True),
    sa.Column('ALMARAI BLU 500GX2 GLASS(SP.PR)', sa.FLOAT(), nullable=True),
    sa.Column('LVQR  TR.P 120GR', sa.FLOAT(), nullable=True),
    sa.Column('LVQR  TR.P 480GR', sa.FLOAT(), nullable=True),
    sa.Column('LVQR  TR.P 360GR', sa.FLOAT(), nullable=True),
    sa.Column('LVQR  TR.P 240GR', sa.FLOAT(), nullable=True),
    sa.Column('LVQR TR 120GX5 (4+1 FR)', sa.FLOAT(), nullable=True),
    sa.Column('LVQR TR 480GX2(SP.PRICE)', sa.FLOAT(), nullable=True),
    sa.Column('LVQR  TUB 200GR', sa.FLOAT(), nullable=True),
    sa.Column('LVQR  TUB 500GR', sa.FLOAT(), nullable=True),
    sa.Column('JAW  TUB480GR', sa.FLOAT(), nullable=True),
    sa.Column('JAW  TR.P 480GR', sa.FLOAT(), nullable=True),
    sa.Column('JAW  TR.P 120GR', sa.FLOAT(), nullable=True),
    sa.Column('JAW  TR.P 240GR', sa.FLOAT(), nullable=True),
    sa.Column('JAW TR 120GX4 (S.P)', sa.FLOAT(), nullable=True),
    sa.Column('JAW TR 120GX5 (8PO)(SP)', sa.FLOAT(), nullable=True),
    sa.Column('PUCK  SQ.P 108GR', sa.FLOAT(), nullable=True),
    sa.Column('PUCK  SQ.P 216GR', sa.FLOAT(), nullable=True),
    sa.Column('PUCK  SQ.P 432GR', sa.FLOAT(), nullable=True),
    sa.Column('PUCK 500GX2 GLASS BLUE(SP.PRICE)', sa.FLOAT(), nullable=True),
    sa.Column('PUCK 910GX2 JAR BLUE (SP.PRICE)', sa.FLOAT(), nullable=True),
    sa.Column('PUCK GLASS BLU  240GR', sa.FLOAT(), nullable=True),
    sa.Column('PUCK GLASS BLU  500GR', sa.FLOAT(), nullable=True),
    sa.Column('PUCK GLASS BLU  910GR', sa.FLOAT(), nullable=True),
    sa.Column('PUCK GLASS BLU  1100GR', sa.FLOAT(), nullable=True),
    sa.Column('PUCK TR 120GX5 (4+1 FREE)', sa.FLOAT(), nullable=True),
    sa.Column('PUCK 650GR JAR(30% EXTR A) (BLUE)', sa.FLOAT(), nullable=True),
    sa.Column('SALIM  TR.P 120GR', sa.FLOAT(), nullable=True),
    sa.Column('PRESIDENT TR 120GX5 (4+1FR)', sa.FLOAT(), nullable=True),
    sa.Column('NADEC  TR.P 120GR', sa.FLOAT(), nullable=True),
    sa.Column('NADEC 500GX2 GLASS BLUE (SP.PRICE)', sa.FLOAT(), nullable=True),
    sa.Column('NADEC 500GX2 GLASS GOLD (SP PRICE)', sa.FLOAT(), nullable=True),
    sa.Column('NADEC GLASS BLU  500GR', sa.FLOAT(), nullable=True),
    sa.Column('NADEC TR 120GX5 (4+1 FREE)', sa.FLOAT(), nullable=True),
    sa.Column('KIRI SQ 216GX3 (SP. PRICE)', sa.FLOAT(), nullable=True),
    sa.Column('KIRI SQ 432GX2 (SP.P)', sa.FLOAT(), nullable=True),
    sa.Column('KIRI SQ 108GX5 (SP.P)', sa.FLOAT(), nullable=True),
    sa.Column('KIRI  SQ.P 324GR', sa.FLOAT(), nullable=True),
    sa.Column('KIRI  SQ.P 432GR', sa.FLOAT(), nullable=True),
    sa.Column('KIRI  SQ.P 108GR', sa.FLOAT(), nullable=True),
    sa.Column('KIRI  SQ.P 216GR', sa.FLOAT(), nullable=True),
    sa.Column('KIRI  TUB 350GR', sa.FLOAT(), nullable=True),
    sa.Column('KIRI  TUB 500GR', sa.FLOAT(), nullable=True),
    sa.Column('KIRI SQ 108GX5 (1 FREE)', sa.FLOAT(), nullable=True),
    sa.Column('KIRI SQ 432GX3(24P)(SP.P)', sa.FLOAT(), nullable=True),
    sa.Column('KRAFT GLASS480GX2 GOLD JAR(SP)', sa.FLOAT(), nullable=True),
    sa.Column('KRAFT 870GX2GOLD JAR(SP)', sa.FLOAT(), nullable=True),
    sa.Column('PHILADELPHIA  TUB 200GR', sa.FLOAT(), nullable=True),
    sa.Column('PHILADELPHIA  TUB 300GR', sa.FLOAT(), nullable=True),
    sa.Column('PHILADELPHIA  TUB  300GR', sa.FLOAT(), nullable=True),
    sa.Column('PHILADELPHIA  TUB 500GR', sa.FLOAT(), nullable=True),
    sa.Column('PHILADELPHIA  TUB 1650GR', sa.FLOAT(), nullable=True),
    sa.Column('PHILADELPHIA  TUB  200GR', sa.FLOAT(), nullable=True),
    sa.Column('JAW 8 PIECES 120 GR', sa.FLOAT(), nullable=True),
    sa.Column('JAW 480X2 32X2', sa.FLOAT(), nullable=True),
    sa.Column('KIRI SP Greek Style 6p', sa.FLOAT(), nullable=True),
    sa.Column('KIRI SP Greek style 24p', sa.FLOAT(), nullable=True),
    sa.Column('KIRI Jars 240g', sa.FLOAT(), nullable=True),
    sa.Column('KIRI Jars 440g', sa.FLOAT(), nullable=True),
    sa.Column('KIRI Jars 600g', sa.FLOAT(), nullable=True),
    sa.Column('KIRI Tubs Greek style 200g', sa.FLOAT(), nullable=True),
    sa.Column('KIRI Tubs Greek style 500g', sa.FLOAT(), nullable=True),
    sa.Column('JAW Jar 240g', sa.FLOAT(), nullable=True),
    sa.Column('JAW Jar 500g', sa.FLOAT(), nullable=True),
    sa.Column('JAW Jar 900g', sa.FLOAT(), nullable=True),
    sa.Column('LVQR TR.P Organic 8p', sa.FLOAT(), nullable=True),
    sa.Column('-0.4', sa.FLOAT(), nullable=True),
    sa.Column('-0.35', sa.FLOAT(), nullable=True),
    sa.Column('-0.3', sa.FLOAT(), nullable=True),
    sa.Column('-0.25', sa.FLOAT(), nullable=True),
    sa.Column('-0.2', sa.FLOAT(), nullable=True),
    sa.Column('-0.15', sa.FLOAT(), nullable=True),
    sa.Column('-0.1', sa.FLOAT(), nullable=True),
    sa.Column('-0.05', sa.FLOAT(), nullable=True),
    sa.Column('0', sa.FLOAT(), nullable=True),
    sa.Column('0.05', sa.FLOAT(), nullable=True),
    sa.Column('0.1', sa.FLOAT(), nullable=True),
    sa.Column('0.15', sa.FLOAT(), nullable=True),
    sa.Column('0.200000000000001', sa.FLOAT(), nullable=True),
    sa.Column('0.250000000000001', sa.FLOAT(), nullable=True),
    sa.Column('0.300000000000001', sa.FLOAT(), nullable=True),
    sa.Column('0.350000000000001', sa.FLOAT(), nullable=True),
    sa.Column('0.400000000000001', sa.FLOAT(), nullable=True)
    )
    # ### end Alembic commands ###
