"""empty message

Revision ID: ef4a3744075f
Revises: 48f3f5b3c64b
Create Date: 2020-12-30 19:54:56.895563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef4a3744075f'
down_revision = '48f3f5b3c64b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('init_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company', sa.Integer(), nullable=True),
    sa.Column('group_brand', sa.Text(), nullable=False),
    sa.Column('group_size', sa.Integer(), nullable=True),
    sa.Column('group_segments', sa.Text(), nullable=False),
    sa.Column('group_manufacturer', sa.Text(), nullable=False),
    sa.Column('base_sop', sa.Float(), nullable=True),
    sa.Column('old_sop', sa.Float(), nullable=True),
    sa.Column('new_sop', sa.Float(), nullable=True),
    sa.Column('base_volume_share', sa.Float(), nullable=True),
    sa.Column('old_volume_share', sa.Float(), nullable=True),
    sa.Column('new_volume_share', sa.Float(), nullable=True),
    sa.Column('base_wd', sa.Float(), nullable=True),
    sa.Column('new_wd', sa.Float(), nullable=True),
    sa.Column('sales', sa.Float(), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('new_price', sa.Float(), nullable=False),
    sa.Column('base_size', sa.Float(), nullable=True),
    sa.Column('new_size', sa.Float(), nullable=True),
    sa.Column('index_volume_share', sa.Float(), nullable=True),
    sa.Column('base_value_sales', sa.Float(), nullable=True),
    sa.Column('base_value_share', sa.Float(), nullable=True),
    sa.Column('new_value_sales', sa.Float(), nullable=True),
    sa.Column('diff_value_sales', sa.Float(), nullable=True),
    sa.Column('new_value_share', sa.Float(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_init_data_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_init_data')),
    sa.UniqueConstraint('sku_name', name=op.f('uq_init_data_sku_name'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('init_data')
    # ### end Alembic commands ###
